apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  database_url: "postgres://user:password@hostname:5432/database"
  log_level: "INFO"
  external_api_url: "https://api.example.com"
  # multi_text
  multiline_config: |
    line1
    line2
    line3